### ISSUE TITLE
Override alpinejs error handler to intercept all errors

### ISSUE THREAD

**Issue by patinthehat** [permafrost-dev/alpinejs-ray#1]
Intercept all errors from alpinejs that start with "Alpine Error: " and send them to Ray instead.

Reference: [alpinejs/src/utils.js#L68](https://github.com/alpinejs/alpine/blob/master/src/utils.js#L68)

@HugoDF any help or insight on this would be appreciated.

**Comment by HugoDF** [comment]
Yeah so you can listen for errors using addEventListener, see

https://github.com/alpine-collective/alpinejs-devtools/blob/master/packages/shell-chrome/src/backend.js#L79-L90

And the relevant errors will have `el` and `expression` attached

**Comment by patinthehat** [comment]
Thanks for the quick reply :pray: 
Do you know if it will avoid the console warnings altogether?

**Comment by HugoDF** [comment]
> Thanks for the quick reply :pray: 
> Do you know if it will avoid the console warnings altogether?

Not with this approach, you can just overwrite the console, in that same file there's code that overwrites console.warn for Alpine 2.8.0 which didn't attach the data to the error being thrown
