### ISSUE TITLE
Error when adding alpinejs-ray to Alpine Version 3 project

### ISSUE THREAD

**Issue by janhendrik-rust** [permafrost-dev/alpinejs-ray#19]
**Describe the bug**

When I add alpinejs-ray to an Alpine V3.2.3 project I get the following error in the console

`alpine.js?id=a3692cc7446e217f9238:2 Uncaught TypeError: e.Alpine.addMagicProperty is not a function
    at Object.start (alpine.js?id=a3692cc7446e217f9238:2)
    at alpine.js?id=a3692cc7446e217f9238:2
    at alpine.js?id=a3692cc7446e217f9238:2
    at alpine.js?id=a3692cc7446e217f9238:2`

`Uncaught TypeError: Cannot read property 'parentElement' of undefined
    at Yn (alpine.js?id=a3692cc7446e217f9238:2)
    at alpine.js?id=a3692cc7446e217f9238:2`

**To Reproduce**

1. create a new project with latest alpine js (v3.2.3 at this time) and alpinejs-ray
`"dependencies": { "alpinejs": "^3.2.3", "alpinejs-ray": "^1.4.0", }`

2. Add alpinejs-ray to your alpine config
`import { Ray, ray } from 'node-ray/web';` 
`import Alpine from 'alpinejs';`
`import AlpineRayPlugin from 'alpinejs-ray';`
`window.alpineRayConfig = {`
`    logComponentsInit: true,`
`    logCustomEvents: false,`
`    interceptErrors: true,`
`    interceptSpruce: true,`
`};`
`window.ray = ray;`
`window.Ray = Ray;`
`window.axios = require('axios');`
`window.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';`
`window.Alpine = Alpine;`
`window.AlpineRayPlugin = AlpineRayPlugin;`
`window.AlpineRayPlugin.init();`
`window.AlpineRayPlugin.start();`
`Alpine.start()`

3. Start you webserver and load a page including the alpinejs refference

`alpine.js?id=a3692cc7446e217f9238:2 Uncaught TypeError: e.Alpine.addMagicProperty is not a function
    at Object.start (alpine.js?id=a3692cc7446e217f9238:2)
    at alpine.js?id=a3692cc7446e217f9238:2
    at alpine.js?id=a3692cc7446e217f9238:2
    at alpine.js?id=a3692cc7446e217f9238:2`

**Expected behavior**

When adding alpinejs-ray to an alpine project the plugin should be loaded successfully

**Screenshots**

None

**Environment (please complete the following information):**

 - OS: Linux
 - Laravel Version: 8
 - Language: Vanilla Javascript

**Comment by janhendrik-rust** [comment]
Sorry I missed your comment on the pull request.
You're welcome to close this issue or use it as a reminder to merge the PR #17  .
I also thought it might help someone who gets the same error, find the PR in google.

**Comment by jensolafkoch** [comment]
I get a similar error from utils.ts

`Uncaught TypeError: can't access property "parentElement", n is undefined`

followed by an Alpine error

`Uncaught (in promise) ReferenceError: $ray is not defined`

alpinejs-ray included via CDN here.

**Comment by patinthehat** [comment]
This will be resolved in the upcoming v2.0 release, which adds support for Alpine v3.

**Comment by patinthehat** [comment]
@janhendrik-rust @jensolafkoch 

Version 2.0 of `alpinejs-ray` has been [released](https://github.com/permafrost-dev/alpinejs-ray/releases/tag/v2.0.0) which adds support for Alpine v3.
